"""Add is_assistant column to users table

Revision ID: 6c0a61f2e068
Revises: 8d42f8d3791e
Create Date: 2025-03-17 10:23:45.613822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0a61f2e068'
down_revision: Union[str, None] = '8d42f8d3791e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_messages_user_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('escalations_user_id_fkey', 'escalations', type_='foreignkey')
    op.drop_constraint('escalations_message_id_fkey', 'escalations', type_='foreignkey')
    op.create_foreign_key(None, 'escalations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'escalations', 'chat_messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_assistant', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_assistant')
    op.drop_constraint(None, 'escalations', type_='foreignkey')
    op.drop_constraint(None, 'escalations', type_='foreignkey')
    op.create_foreign_key('escalations_message_id_fkey', 'escalations', 'chat_messages', ['message_id'], ['id'])
    op.create_foreign_key('escalations_user_id_fkey', 'escalations', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_user_id_fkey', 'chat_messages', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
